In [1]:
# 1) Combining a one and a two-dimensional NumPy Array

import numpy as np

arr1 = np.array([1, 2, 3])          # 1D array
arr2 = np.array([[4, 5, 6]])        # 2D array

combined = np.vstack((arr1, arr2))

print("Combined Array:")
print(combined)

Combined Array:
[[1 2 3]
 [4 5 6]]


In [2]:
# 2) Flatten a 2D NumPy Array into 1D Array

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print("Original Array:")
print(arr)

print("\nFlattened Array:")
print(flat)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]


In [3]:
# 3) Reverse a NumPy Array

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reverse_arr)

Original Array: [10 20 30 40 50]
Reversed Array: [50 40 30 20 10]


In [4]:
# 4) Practice Operations
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# Maximum value
print("Maximum Value:", np.max(arr))

# Minimum value
print("Minimum Value:", np.min(arr))

# Number of rows and columns
rows, cols = arr.shape
print("Rows:", rows)
print("Columns:", cols)

# Each element
print("\nAll Elements:")
for row in arr:
    for element in row:
        print(element)

# Specific element
print("\nSpecific Element [1][2]:", arr[1][2])

# Sum using for loop
total = 0
for row in arr:
    for element in row:
        total += element

print("Sum using for loop:", total)

Maximum Value: 60
Minimum Value: 10
Rows: 2
Columns: 3

All Elements:
10
20
30
40
50
60

Specific Element [1][2]: 60
Sum using for loop: 210


In [5]:
# Adding, Subtracting, Multiplying, Dividing Arrays
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [6]:
# 5) Iterate 3D Array using for loop

import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Iterating 3D Array using for loops:")

for block in arr:
    for row in block:
        for element in row:
            print(element)

Iterating 3D Array using for loops:
1
2
3
4
5
6
7
8


In [7]:
# Iterate 3D Array using nditer

import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Iterating using nditer:")

for x in np.nditer(arr):
    print(x)

Iterating using nditer:
1
2
3
4
5
6
7
8


In [8]:
# 6) Average of Two NumPy Arrays

import numpy as np

arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

avg = (arr1 + arr2) / 2

print("Average of NumPy arrays:")
print(avg)

Average of NumPy arrays:
[2. 2.]


In [10]:
# Mean, Median, Mode of Two NumPy 2D Arrays

import numpy as np
from scipy import stats

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

combined = np.concatenate((arr1.flatten(), arr2.flatten()))

print("Combined Data:")
print(combined)

# Mean
mean_value = np.mean(combined)
print("\nMean:", mean_value)

# Median
median_value = np.median(combined)
print("Median:", median_value)

# Mode
mode_value = stats.mode(combined, keepdims=True)

print("Mode:", mode_value.mode[0])
print("Frequency:", mode_value.count[0])

Combined Data:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Mean: 6.5
Median: 6.5
Mode: 1
Frequency: 1
