In [1]:
import numpy as np

# 1) Replace NaN with 0 and interchange rows & columns (transpose)
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr_no_nan = np.nan_to_num(arr, nan=0)

print("Array after replacing NaN with 0:")
print(arr_no_nan)

# Interchange rows and columns
transpose_arr = arr_no_nan.T

print("\nTranspose of array:")
print(transpose_arr)


Array after replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Transpose of array:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
# 2) Move axes of 3D array to new positions
arr3d = np.arange(24).reshape(2, 3, 4)

print("\nOriginal 3D Array Shape:")
print(arr3d.shape)

# Move axis 0 to position 2
moved_arr = np.moveaxis(arr3d, 0, 2)

print("\nArray shape after moving axes:")
print(moved_arr.shape)

print(moved_arr)


Original 3D Array Shape:
(2, 3, 4)

Array shape after moving axes:
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
# 3) Replace NaN values with average of columns
arr2 = np.array([[1, 2, np.nan],
                 [4, np.nan, 6],
                 [7, 8, 9]])

print("\nOriginal Array:")
print(arr2)

# Calculate column averages ignoring NaN
col_mean = np.nanmean(arr2, axis=0)

# Find indices where NaN exists
inds = np.where(np.isnan(arr2))

# Replace NaN with column mean
arr2[inds] = np.take(col_mean, inds[1])

print("\nArray after replacing NaN with column average:")
print(arr2)


Original Array:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

Array after replacing NaN with column average:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
# 4) Replace negative values with zero
arr3 = np.array([5, -2, 7, -9, 10, -1])

print("\nOriginal Array:")
print(arr3)

# Replace negative values with 0
arr3[arr3 < 0] = 0

print("\nArray after replacing negative values with 0:")
print(arr3)


Original Array:
[ 5 -2  7 -9 10 -1]

Array after replacing negative values with 0:
[ 5  0  7  0 10  0]
